SELECT fi.ID, fni.FISH_NAME, fi.LENGTH
FROM FISH_INFO AS fi
JOIN FISH_NAME_INFO AS fni ON fi.FISH_TYPE = fni.FISH_TYPE
WHERE fi.LENGTH = (SELECT MAX(LENGTH) FROM FISH_INFO ifi WHERE ifi.FISH_TYPE=fi.FISH_TYPE)
ORDER BY fi.ID ASC